### ISSUE TITLE
8월 12일 회의사항

### ISSUE THREAD

**Issue by sungkuk5420** [sungkuk5420/CarRepairShopApp#113]
- [x] 일주일 진행사항 간판 확인
- [x] 이번주 다음주 진행 내용 작성
- [x] 질문, 이슈, 등등 공유하기
- [x] 슬랙 올스레드 확인. 
- [x] 프로젝트 전체 구성 다시 살펴보기.

남은과제 
■퍼블리싱 
  - 마이페이지 ( 이줠 )
  - 개인정보 동의. (서비스 이용약관)  ( 이줠 )

■디자인 시안 내기
  - 로그인
  - 회원가입
  - 개인정보 공유 
------------------------------------------------------------------------
  - 메인 ( 완료 ) 
  - 이벤트 ( 완료 ) 
  - 공업사 ( 완료 ) 
  - 견적요청 ( 완료 ) 
  - 마이페이지 ( 완료 ) 

■디자인 입히기 
  - 로그인
  - 회원가입
  - 메인
  - 이벤트 ( 완료 ) 
  - 공업사
  - 견적요청
  - 마이페이지
  - 개인정보 공유 

■기능구현
  - 견적 요청시 예약기록 남기기 DB (윤기)
  - 회원가입 중복검사 (현동이형)
  - 코멘트 기능 
  - 설정쪽 로그아웃
  - 예약 현황 연동 
  - 회원정보 수정. 
  - 푸시 테스트. (성국)
  - 전화번호 연동.  (성국)
  - 코르도바 패키징. (성국)
  - 카메라 어플 연동해서 네이티브로 사진 올리기.  (성국)
  - 데이터 베이스 파베 갱신 (key가 노출됌) (성국)
  - 웹 매니 패스트 (성국)
  - 웹 워커 서비스 (성국)
  - 도메인 연동 잘되었는지 확인 (성국)
  - 실 운영 서버에 업로드  (성국)
------------------------------------------------------------------------
  - 세션작업 ( 완료 - 카카오, 페이스북, 네이버 , 로컬 )  
  - 이미지 압축 (완료 - 불필요해짐.)
  - s3 이미지 업로드  ( 완료 ) 
  - 지도 표시  ( 완료 )

**Comment by sungkuk5420** [comment]
@dodongworld 안동 확인점

다음주 작업내용 할당해줘 개인적으로 디자인입히는거 페이지 1개씩 담당하면 좋을듯.

**Comment by syg1138** [comment]
이번주 작업한 내용
#94 견적요청서 firebase에 저장
#103 개인정보 동의(서비스 이용약관) 퍼블리싱

다음주 작업할 내용

**Comment by shd8989** [comment]
이번주 작업한 내용
#105 회원가입 중복확인
#91 마이페이지 작업중

다음주 작업할 내용
#91 마이페이지, 마이페이지 수정 화면

**Comment by seungtae97** [comment]
이번주 작업한내용
없음

다음주작업할내용
#118 로그인 및 회원가입 페이지 디자인

**Comment by dodongworld** [comment]
이번주 작업한 내용
#110 GUI 가이드 제작하기
-> 저작권 관련 이슈로 제작시 매우 리소스가 클 예정
-> PSD에 가이드 레이어 추가하는 방식으로 진행
-> 기존 디자인 파일 외 가이드 이미지 포함 전달 예정

다음주 작업할 내용
#117 개인정보, 이용약관 페이지 기획 및 디자인

**Comment by dodongworld** [comment]
[이슈]
1. 태블릿, 가로모드 제작 관련
-> 미디어쿼리 사용하지 않으면 반응형에 어려움이 있음
-> 디자인, 디자인가이드 추가로 제작해야함.

**Comment by kimc159** [comment]
이번주 작업한 내용
#86 css 수정

다음주 작업할 내용
#86 이벤트, 이벤트 상세 페이지 반응형

**Comment by sungkuk5420** [comment]
@jeonjeehye 전졔 저번주 작업내용, 이번주 할내용 적어주세요.

**Comment by sungkuk5420** [comment]
■이번주 작업한 내용
#89 리뷰하기
#112 리뷰하기
#80 리뷰하기
■다음주 작업할 내용(19일까지)
#90 로컬 로그인 세션유지작업.
#100 이슈, 풀리퀘 템플릿 만들기
#101 코르도바 테스트
