### ISSUE TITLE
개인정보 처리방침 표시 페이지 필요함.

### ISSUE THREAD

**Issue by sungkuk5420** [sungkuk5420/CarRepairShopApp#123]
페이스북 로그인을 공개하기 위해서는 해당 정보를 어떻게 관리하겠다고 유저들에게 공지해야함. 그전에 공개불가능.

![image](https://user-images.githubusercontent.com/16679303/44300157-327a2b80-a33d-11e8-9e05-48b0bc3bd79c.png)

**Comment by dodongworld** [comment]
문구 구성 완료함
디자인후  
#117 개인정보, 이용약관 페이지 기획 및 디자인 이슈에 통합함.

**Comment by sungkuk5420** [comment]
@dodongworld 땡큐! 이 이슈는 작업완료로 옮길게

**Comment by sungkuk5420** [comment]
@dodongworld 
안동개인정보동의문구
윤기한테전달해줘 지금페이지작업중이라서
