### ISSUE TITLE
8월19일회의진행사항

### ISSUE THREAD

**Issue by kimc159** [sungkuk5420/CarRepairShopApp#124]
- [x] 일주일 진행사항 간판 확인
- [x] 이번주 다음주 진행 내용 작성
- [x] 질문, 이슈, 등등 공유하기
- [x] 슬랙 올스레드 확인.
- [x] 프로젝트 전체 구성 다시 살펴보기.

남은과제

■디자인 시안 내기

로그인
회원가입
메인 ( 완료 )
이벤트 ( 완료 )
이벤트상세( 완료 )
공업사 ( 완료 )
견적요청 ( 완료 )
마이페이지 ( 완료 )
개인정보 공유
■디자인 입히기

로그인
회원가입
메인(윤기)
이벤트 ( 완료 )
이벤트상세( 완료 )
공업사(윤기)
견적요청(주열)
마이페이지(현동이형)
개인정보 공유
■기능구현
개인정보 동의 화면 내용 채우기
견적 요청시 예약기록 남기기 DB (완료)
회원가입 중복검사 (현동이형)
코멘트 기능
설정쪽 로그아웃
예약 현황 연동
회원정보 수정.
푸시 테스트. (성국)
전화번호 연동. (성국)
코르도바 패키징. (성국)
카메라 어플 연동해서 네이티브로 사진 올리기. (성국)
데이터 베이스 파베 갱신 (key가 노출됌) (성국)
웹 매니 패스트 (성국)
웹 워커 서비스 (성국)
도메인 연동 잘되었는지 확인 (성국)
실 운영 서버에 업로드 (성국)
세션작업 ( 완료 - 카카오, 페이스북, 네이버 , 로컬 )
이미지 압축 (완료 - 불필요해짐.)
s3 이미지 업로드 ( 완료 )
지도 표시 ( 완료 )

**Comment by seungtae97** [comment]
이번주 작업한내용
없음

다음주작업할내용
#118 로그인 및 회원가입 페이지 디자인
개인정보 공유 제작

**Comment by syg1138** [comment]
이번주 작업한 내용
#103 개인정보 동의, 서비스 이용약관
#119 메인페이지 퍼블리싱
#121 공업사 페이지 퍼블리싱
다음주 작업할 내용
#119 메인페이지 퍼블리싱(이벤트 항목 퍼블리싱)
#121 공업사 페이지 퍼블리싱

**Comment by sungkuk5420** [comment]
@kimc159 @seungtae97 @syg1138 @dodongworld @shd8989 @jeonjeehye 
#113 이거 참고해서 작성하세요 12일 회의진행사항입니다.

**Comment by kimc159** [comment]
이번주 작업한 내용
#86 event, event_detail 반응형 퍼블리싱 및 footer 반응형 css

다음주 작업할 내용
#125 견적요청 퍼블리싱

**Comment by shd8989** [comment]
이번주 작업한 내용
#104 지도 도메인 변경 진행중

다음주 작업할 내용
#91 마이페이지
#105 중복확인 함수 수정

회사일이 바빠 진행이 더딘점 죄송하게 생각하고 있습니다.

**Comment by sungkuk5420** [comment]
■이번주 작업한 내용
#90 로컬 로그인 세션유지작업.
#106 소셜로그인 도메인 변경작업.
리뷰 #78 #99 #85 
■다음주 작업할 내용
#100 이슈, 풀리퀘 템플릿 만들기
#127 웹매니페스트 설정.
#132
#131
#101 코르도바 테스트

**Comment by jeonjeehye** [comment]
■이번주 작업한 내용
디자인 페이지 아이콘 카톡 공유
■다음주 작업할 내용
#137 웹앱 아이콘 디자인
