### ISSUE TITLE
8월 26일 회의진행사항

### ISSUE THREAD

**Issue by sungkuk5420** [sungkuk5420/CarRepairShopApp#133]
- [x] 일주일 진행사항 간판 확인
- [x] 이번주 다음주 진행 내용 작성
- [x] 질문, 이슈, 등등 공유하기
- [x] 슬랙 올스레드 확인.
- [x] 프로젝트 전체 구성 다시 살펴보기.

남은과제

■디자인 시안 내기

로그인
회원가입
메인 ( 완료 )
이벤트 ( 완료 )
이벤트상세( 완료 )
공업사 ( 완료 )
견적요청 ( 완료 )
마이페이지 ( 완료 )
내차량 페이지( 완료 )#97 
개인정보 공유
■디자인 입히기

로그인
회원가입
메인(완료)
이벤트 ( 완료 )
이벤트상세( 완료 )
공업사(완료)
견적요청(주열 - 30)
마이페이지(현동이형 - 30)
내차량 페이지
개인정보 공유 

■기능구현
앱 스플래시 화면
앱 아이콘
개인정보 동의 화면 내용 채우기 (윤기)
견적 요청시 예약기록 남기기 DB (완료)
회원가입 중복검사 (현동이형)
코멘트 기능
설정쪽 로그아웃
설정쪽 로그인 유저 정보 표시.
예약 현황 연동.
회원정보 수정.
푸시 테스트. (성국)
전화번호 연동. (성국)
★코르도바 패키징. (성국) -> pwa앱인데 꼭 필요한가? 만약 기능상 제약이 있다면 ㄱㄱ 
웹 워커 서비스 (성국)
카메라 어플 연동해서 네이티브로 사진 올리기. (완료)
웹 매니 패스트 (완료) 
세션작업 ( 완료 - 카카오, 페이스북, 네이버 , 로컬 )
이미지 압축 (완료 -  다시 병합함.)
s3 이미지 업로드 ( 완료 )
지도 표시 ( 완료 )

■마지막 확인사항

데이터 베이스 파베 갱신 (key가 노출됌) (성국)
도메인 연동 잘되었는지 확인 (성국) 소셜 로그인, 지도,
실 운영 서버에 업로드 (성국)

**Comment by sungkuk5420** [comment]
■이번주 작업한 내용
#100 이슈, 풀리퀘 템플릿 만들기
#127 웹매니페스트 설정.
#132 pwa에서 a태그로 페이지 이동시 웹페이지로 이동되버림
#131 앱스플래시 화면설정.
■다음주 작업할 내용
#134 카메라 어플 연동해서 네이티브로 사진 올리기.
전화번호 연동.
#101 코르도바 테스트

**Comment by kimc159** [comment]
■이번주 작업한 내용
#130 견적요청 퍼블리싱 30% 완료
■다음주 작업할 내용
#141 로그인,회원가입 퍼블리싱 수정

**Comment by syg1138** [comment]
이번주 작업한 내용
#119 메인페이지 퍼블리싱(완료)
#121 공업사 페이지 퍼블리싱(완료)
다음주 작업할 내용
#103 개인정보 동의 서비스 이용약관(레이아웃 재정의 및 약관 내용 넣기)
#130 견적요청 퍼블리싱

**Comment by sungkuk5420** [comment]
더이상 작업이 진행되지 않아 26일 회의 마감처리합니다.
이후로는 회의 없이 진행합니다.
