### ISSUE TITLE
반응형 대응하기 위한 기본 틀 제작 

### ISSUE THREAD

**Issue by sungkuk5420** [sungkuk5420/CarRepairShopApp#17]
모든 페이지는 모바일 우선 반응형으로 제작될것이며 이를 위한 틀(컨테이너)를 짜놓는다.

모든 개발자는 해당 샘플을 이용하여 틀을 잡아놓고 개발을 진행한다.

**Comment by sungkuk5420** [comment]
@shd8989 

담당자 현동이형으로 변경.

**Comment by shd8989** [comment]
나니?

**Comment by sungkuk5420** [comment]
@shd8989 ㅋㅋㅋㅋㅋ
댓글달때엔 @로 태그도 함께해주세요 알람이 안떠요

**Comment by sungkuk5420** [comment]
@shd8989 
다시 담당자 저로 변경할게요.

**Comment by sungkuk5420** [comment]
@kimc159 머지했으므로 해당 이슈 완료 처리함
