### ISSUE TITLE
홈 > 공업소  > 실시간 견적

### ISSUE THREAD

**Issue by sungkuk5420** [sungkuk5420/CarRepairShopApp#23]
홈 > 공업사 > 실시간 견적

![image](https://user-images.githubusercontent.com/16679303/40576262-d74825ce-612d-11e8-811e-ad91eb2b770f.png)

**Comment by sungkuk5420** [comment]
@kimc159 
이거 해보셈

**Comment by kimc159** [comment]
@sungkuk5420  완료했음

**Comment by sungkuk5420** [comment]
@kimc159 수고하셨습니다 기능구현도 이쪽에서 마무리했습니다.
