### ISSUE TITLE
용어 정리

### ISSUE THREAD

**Issue by sungkuk5420** [sungkuk5420/CarRepairShopApp#3]
위키에 용어 정리할것

ex)

Node Js
![image](https://user-images.githubusercontent.com/16679303/40034011-f97e92aa-5835-11e8-9e8b-077a90cc33a0.png)

Express
Node Js 의 서버사이드 프레임워크

Git
소스관리 툴

GitHub
소스코드 저장소

**Comment by sungkuk5420** [comment]
git 
gitHub
sourcetree

git push 
git pull
git commit

git branch

**Comment by seungtae97** [comment]
git
- 소스를 관리하는 툴

——

gitHub
- 관리된 소스를 저장하는 곳 (원격 저장소)

——

sourcetree
- git과 github를 관리하는 툴

——

stage
- 작업한 내용이 올라가는 임시 저장 영역입니다. 이 영역을 이용하여 작업한 내용 중 커밋에 반영할 파일만 선별하여 커밋을 수행할 수 있음

——

git commit
- 작업한 내용을 로컬 저장소에 저장하는 과정

——

git push
- 로컬 저장소의 내용 중 원격 저장소에 반영되지 않은 커밋을 원격 저장소로 보내는 과정

——

git pull
- 푸시와 반대로 원격 저장소에 있는 내용 중 로컬 저장소에 반영되지 않은 내용을 가져와서 로컬 저장소에 저장하는 과정

——

git branch
- 커밋을 단위로 구분된 소스코드 타임라인에서 분기해서 새로운 커밋을 쌓을 수 있는 가지를 만드는 것, 혹은 그 가지를 말함

**Comment by seungtae97** [comment]
git
- 소스를 관리하는 툴

——

gitHub
- 관리된 소스를 저장하는 곳 (원격 저장소)

——

sourcetree
- git과 github를 관리하는 툴

——

stage
- 작업한 내용이 올라가는 임시 저장 영역입니다. 이 영역을 이용하여 작업한 내용 중 커밋에 반영할 파일만 선별하여 커밋을 수행할 수 있음

——

git commit
- 작업한 내용을 로컬 저장소에 저장하는 과정

——

git push
- 로컬 저장소의 내용 중 원격 저장소에 반영되지 않은 커밋을 원격 저장소로 보내는 과정

——

git pull
- 푸시와 반대로 원격 저장소에 있는 내용 중 로컬 저장소에 반영되지 않은 내용을 가져와서 로컬 저장소에 저장하는 과정

——

git branch
- 커밋을 단위로 구분된 소스코드 타임라인에서 분기해서 새로운 커밋을 쌓을 수 있는 가지를 만드는 것, 혹은 그 가지를 말함

——

Pull request
- 내가 작업한 소스코드들을 github에 올려 검토를 요청하는것으로, 프로젝트 관리자는 Pull request를 확인후 메인 branch에 합병할 수 있음. 이 과정에서 관리자및 협업자들에게 코드리뷰를 받을 수 있음

**Comment by sungkuk5420** [comment]
@seungtae97 

위키에 따로 등록해뒀어
<a href="https://github.com/sungkuk5420/carRepairShopApp/wiki/%EC%9A%A9%EC%96%B4-%EC%A0%95%EB%A6%AC"> 위키 용어정리</a>

앞으로 계속 용어 추가해가면서 정보 공유하자.

**Comment by sungkuk5420** [comment]
@seungtae97 일단 클로우즈함.
