### ISSUE TITLE
5 / 27 회의 진행사항

### ISSUE THREAD

**Issue by sungkuk5420** [sungkuk5420/CarRepairShopApp#33]
- [x]  프로젝트 시작전 점검사항 체크
- [x]  일주일간의 해결 이슈 브리핑
- [x]  민이랑 이줠 풀리퀘스트 진행
- [x]  브런치 정리후 전체 동기화
- [x]  브런치 생성 방법 설명
- [x]  이슈작성, 풀리퀘스트 기본 템플릿 작성
- [x]  헤로쿠 리뷰앱 생성법 설명
- [x]  페이지 분담

**Comment by dodongworld** [comment]
<h3>2018.05.27 회의 정리</h3>
<h4>페이지 퍼블리싱</h4>
* 메인 - 안동현
* 로그인 - 김성국
* 공업사 - 서현동
* 이벤트/쿠폰 - 이승태
* 템플릿 - 이주열

<h4>앱 디자인</h4>
* 안동현, 이승태

<h4>디자인 문서화</h4>
* 전지혜

**Comment by sungkuk5420** [comment]
작업 완료 처리합니다.
