### ISSUE TITLE
6월 17일 회의 진행사항

### ISSUE THREAD

**Issue by shd8989** [sungkuk5420/CarRepairShopApp#46]
질문 및 공유사항
6.20 수요일
- UI 가이드 버전합치기
- 현동이형 리뷰하기

6.23 토요일
[디자인 시안 안내]
- UI가이드 v4 상세 제작. (상세 페이지 및 시나리오)

7월 초
- UI가이드 픽스 및 디자인 전달
- 7월초 디자인 가이드 완성 -> 전달
- 7월 초부터 디자인 입히기 작업 시작
- DB 작업은 7월초 UI기획서가 마무리되는대로 진행

**Comment by sungkuk5420** [comment]
감사합니다

**Comment by shd8989** [comment]
수요일
- UI 가이드 버전합치기
- 현동이형 리뷰하기

- 7월초 디자인 가이드 완성 -> 전달
- 7월 초부터 디자인 입히기 작업 시작
- DB 작업은 7월초 UI기획서가 마무리되는대로 진행

**Comment by sungkuk5420** [comment]
이슈 닫을게요.
