### ISSUE TITLE
6월24일 회의 진행사항

### ISSUE THREAD

**Issue by shd8989** [sungkuk5420/CarRepairShopApp#47]
[6월24일 회의록]
페이지 5개 추가
- 공업사 상세
- 개인정보동의
- 견적완료
- 마이페이지 로그인전
- 마이페이지 로그인후

상단 로그인 전/후 화면 수정
하단 메뉴 5가지로 수정

승태 - 이벤트 페이지 풀리퀘스트
지혜 - pdf 업데이트

-----------------------------------------------------------
[6월17일 회의록]
6.20 수요일 예정
UI 가이드 버전합치기
현동이형 리뷰하기

6.23 토요일 예정
[디자인 시안 안내]
UI가이드 v4 상세 제작. (상세 페이지 및 시나리오)

7월 초 예정
UI가이드 픽스 및 디자인 전달
7월초 디자인 가이드 완성 -> 전달
7월 초부터 디자인 입히기 작업 시작
DB 작업은 7월초 UI기획서가 마무리되는대로 진행

**Comment by sungkuk5420** [comment]
확인완료 후 이슈 닫습니다.
