### ISSUE TITLE
GraphQL 구축하기

### ISSUE THREAD

**Issue by shd8989** [sungkuk5420/CarRepairShopApp#55]
https://academy.nomadcoders.co/p/make-a-movie-api-with-graphql-and-nodejs-super-begginner

**Comment by sungkuk5420** [comment]
@shd8989 
브런치 새로 파서 진행해주세요.

**Comment by sungkuk5420** [comment]
본 프로젝트에서 사용 안하기로 결정되었으므로 이슈 폐기합니다.
