### ISSUE TITLE
메뉴 구조도 작성

### ISSUE THREAD

**Issue by sungkuk5420** [sungkuk5420/CarRepairShopApp#6]
아주 간단하게라도 좋음. 

형식은 뭐라도 괜찮아 
손으로 그려도 되고 ppt, web site뭐라도 괜찮으니까 편하게 작성해서 대충 그려줘

ex) 
![image](https://user-images.githubusercontent.com/16679303/40152013-3ceb4b30-59be-11e8-86a6-c83aa54d7b39.png)

한국어 자료를 찾기 힘들어서 키워드를 모르겠지만 여기서는 화면 전이도라고함 

로그인 ->메인페이지　->  게시글 
　　　　　　　　　　  ->   설정창

등등

**Comment by dodongworld** [comment]
@seungtae97 
- 앱 기획 구성 완료
- Adobe XD를 사용하여 시안 제작 중

**Comment by sungkuk5420** [comment]
![image](https://user-images.githubusercontent.com/16679303/40578561-ce611060-6150-11e8-9716-280691b0f382.png)

**Comment by sungkuk5420** [comment]
@dodongworld 

이슈 완료처리합니다.

**Comment by sungkuk5420** [comment]
@dodongworld 이쪽 구조도 수정 완료되면 
위키쪽 디자인 시안 정리에 이미지로 첨부후
이슈 완료 처리 해주세요

**Comment by sungkuk5420** [comment]
![image](https://user-images.githubusercontent.com/16679303/43052841-1a26cacc-8e64-11e8-8d4a-846fbd7b8603.png)

@dodongworld 작업 완료 처리합니다.
