### ISSUE TITLE
7월8일 회의진행사항

### ISSUE THREAD

**Issue by shd8989** [sungkuk5420/CarRepairShopApp#61]
[7월8일 회의록]
이슈 정리

이번주 역할 분담
김성국 - 메인페이지, 로그인 기능 구현, graphQL 서버 구축
서현동 - graphQL 서버 구축, DB 서버 구축, 회원가입 페이지
송윤기 - 이벤트, 견적 완료 페이지 기능(이미지 업로드)
안동현, 이승태, 전지혜 - 디자인
이주열 - 견적 완료 페이지 퍼블리싱

----------------------------------------------------------------------------------
[7월1일 회의록]
추가된 화면 리뷰 및 wiki 업데이트

**Comment by sungkuk5420** [comment]
@shd8989 현동이형 작성 감사합니다.
