### ISSUE TITLE
프로젝트 시작전 점검사항 체크

### ISSUE THREAD

**Issue by sungkuk5420** [sungkuk5420/CarRepairShopApp#7]
<a href="https://github.com/sungkuk5420/carRepairShopApp/wiki/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EC%8B%9C%EC%9E%91%EC%A0%84-%EC%A0%90%EA%B2%80%EC%82%AC%ED%95%AD">프로젝트 시작 전 점검사항</a>

전항목 설치 완료 한사람은 밑에 

- [ ] git 설치 
- [ ] sourceTree  설치 
- [ ] slack 설치 & 가입 ( 민이랑 이줠 안들어와있음)
- [ ] node js 설치(LTS)
- [ ] 개발툴 설치 (아무거나 괜찮음. vscode, webstorm 중 선택하는걸 추천)   
- [ ] GitHub Web 알림 설정
- [ ] CodeHub 어플 설치 (gitHub 어플로 댓글 및 이슈확인가능)

체크해서 댓글 작성해주세요

### 체크박스 입력폼 복사방법
![image](https://user-images.githubusercontent.com/16679303/40286246-68c88b6c-5ce0-11e8-8cbc-7bd9630957d7.png)

여기서 Edit누르고 복사

![image](https://user-images.githubusercontent.com/16679303/40286250-73ac58ce-5ce0-11e8-92ad-0a7f51fccde2.png)

**Comment by sungkuk5420** [comment]
- [ ] git 설치 
- [ ] sourceTree  설치 
- [ ] slack 설치 
- [ ] node js 설치(LTS)
- [ ] 개발툴 설치 (아무거나 괜찮음. vscode, webstorm 중 선택하는걸 추천)

**Comment by dodongworld** [comment]
- [ ] git 설치 
- [ ] sourceTree  설치 
- [ ] slack 설치 
- [ ] node js 설치(LTS)
- [ ] 개발툴 설치 (아무거나 괜찮음. vscode, webstorm 중 선택하는걸 추천)

**Comment by sungkuk5420** [comment]
- [ ] git 설치 
- [ ] sourceTree  설치 
- [ ] slack 설치 
- [ ] node js 설치(LTS)
- [ ] 개발툴 설치 (아무거나 괜찮음. vscode, webstorm 중 선택하는걸 추천)

**Comment by shd8989** [comment]
- [x] git 설치 
- [x] sourceTree  설치 
- [x] slack 설치 & 가입 ( 민이랑 이줠 안들어와있음)
- [x] node js 설치(LTS)
- [x] 개발툴 설치 (아무거나 괜찮음. vscode, webstorm 중 선택하는걸 추천)   
- [x] GitHub Web 알림 설정
- [x] CodeHub 어플 설치 (gitHub 어플로 댓글 및 이슈확인가능)

**Comment by sungkuk5420** [comment]
@jeonjeehye 
이쪽 이슈 확인후 설치하고 댓글달아주세요

**Comment by sungkuk5420** [comment]
- [] git 설치 
- [] sourceTree  설치 
- [] slack 설치 & 가입 ( 민이랑 이줠 안들어와있음)
- [] node js 설치(LTS)
- [x] 개발툴 설치 (아무거나 괜찮음. vscode, webstorm 중 선택하는걸 추천)   
- [x] GitHub Web 알림 설정
- [x] CodeHub 어플 설치 (gitHub 어플로 댓글 및 이슈확인가능)

**Comment by sungkuk5420** [comment]
@KKangMin 민 이쪽 확인후 설치하고 댓글달아줘

**Comment by jeonjeehye** [comment]
- [ ] git 설치 
- [ ] sourceTree  설치 
- [ ] slack 설치 & 가입 ( 민이랑 이줠 안들어와있음)
- [ ] node js 설치(LTS)
- [ ] 개발툴 설치 (아무거나 괜찮음. vscode, webstorm 중 선택하는걸 추천)   
- [ ] GitHub Web 알림 설정
- [ ] CodeHub 어플 설치 (gitHub 어플로 댓글 및 이슈확인가능)

**Comment by sungkuk5420** [comment]
@kimc159 
이주열 여기 확인해서 체크 올려줘

**Comment by KKangMin** [comment]
- [x] git 설치 
- [x] sourceTree  설치 
- [x] slack 설치 & 가입 ( 민이랑 이줠 안들어와있음)
- [ ] node js 설치(LTS)
- [ ] 개발툴 설치 (아무거나 괜찮음. vscode, webstorm 중 선택하는걸 추천)   
- [x] GitHub Web 알림 설정
- [ ] CodeHub 어플 설치 (gitHub 어플로 댓글 및 이슈확인가능)

**Comment by kimc159** [comment]
- [x] git 설치 
- [x] sourceTree  설치 
- [x] slack 설치 
- [x] node js 설치(LTS)
- [x] 개발툴 설치 (아무거나 괜찮음. vscode, webstorm 중 선택하는걸 추천)   
- [x] GitHub Web 알림 설정
- [x] CodeHub 어플 설치 (gitHub 어플로 댓글 및 이슈확인가능)

**Comment by sungkuk5420** [comment]
작업 완료 이슈닫습니다.

**Comment by syg1138** [comment]
- [x] git 설치 
- [x] sourceTree  설치 
- [x] slack 설치 & 가입 ( 민이랑 이줠 안들어와있음)
- [x] node js 설치(LTS)
- [x] 개발툴 설치 (아무거나 괜찮음. vscode, webstorm 중 선택하는걸 추천)   
- [x] GitHub Web 알림 설정
- [x] CodeHub 어플 설치 (gitHub 어플로 댓글 및 이슈확인가능)

**Comment by sungkuk5420** [comment]
@syg1138 
윤기 확인 완료
