### ISSUE TITLE
회원가입 페이지 수정

### ISSUE THREAD

**Issue by syg1138** [sungkuk5420/CarRepairShopApp#76]
1. 차종, 연식 등 (필수) 데이터 입력했는지 확인하고 push
2. 파이어베이스 데이터 push 후 예외처리
 - 에러 발생 시 팝업창 생성
 - 성공 시 3.를 수행
3. 가입완료 시 메인화면으로 이동

**Comment by sungkuk5420** [comment]
@sungkuk-kim-uhuru 리뷰 해주셈

**Comment by sungkuk5420** [comment]
#88 이쪽 풀리퀘임

**Comment by sungkuk5420** [comment]
병합 완료

**Comment by sungkuk5420** [comment]
@syg1138
