### ISSUE TITLE
파일 전달 질문

### ISSUE THREAD

**Issue by seungtae97** [sungkuk5420/CarRepairShopApp#82]
송곳형 psd 파일 같은것들은 깃헙에서 공유 못하나여?

**Comment by seungtae97** [comment]
이거 이슈로 물어봐도 되나...

**Comment by sungkuk5420** [comment]
@seungtae97 라벨 추가해놓긴햇는데ㅋㅋㅋㅋ 제목에 파일 전달 문제 이런식으로 달고
음 psd파일을 이슈쪽 아래 댓글에 파일 첨부로 못올려? 용량제한있으려나

**Comment by sungkuk5420** [comment]
@seungtae97 슬랙들어와봐 질문은 이왕이면 슬랙으로 ㄱ

**Comment by seungtae97** [comment]
그 psd파일은 형식 문제로 못올리네여 ㅠ

**Comment by sungkuk5420** [comment]
@seungtae97 그럼 프로젝트 폴더 master꺼 패치 풀받고 거기안에 디자인 시안 폴더하나 만들어서 커밋 푸시해

**Comment by seungtae97** [comment]
넴 해놓고 작업완료로 옮겨놓겟슴다

**Comment by sungkuk5420** [comment]
그랭

**Comment by sungkuk5420** [comment]
@seungtae97 
승태야 작업완료로 옮길땐 클로우즈도 같이해줘
