### ISSUE TITLE
버튼 및 이미지 아이콘 수정

### ISSUE THREAD

**Issue by kimc159** [sungkuk5420/CarRepairShopApp#86]
버튼 및 이미지 아이콘 수정

**Comment by sungkuk5420** [comment]
@dodongworld @jeonjeehye @seungtae97 

이쪽 확인부탁드립니다

**Comment by jeonjeehye** [comment]
[푸터아이콘.zip](https://github.com/sungkuk5420/CarRepairShopApp/files/2259283/default.zip)
아이콘 수정했는데 어떤게 나을지 몰라서 세가지 버전으로 해봤음.
다시 수정 필요하면 알려줭

**Comment by sungkuk5420** [comment]
@jeonjeehye 전졔 댓글남길땐 이줠을 태그해줘

**Comment by jeonjeehye** [comment]
@kimc159 태그?

**Comment by jeonjeehye** [comment]
@kimc159 그럼 추가로 수정 안해줘도 괜찮은거야?

**Comment by sungkuk5420** [comment]
@syg1138 머지완료하였으니 완료처리합니다

**Comment by sungkuk5420** [comment]
이슈 86 푸터 버튼및이미지아이콘수정,버튼 href 연결,event_detail 데이터 전송
