### ISSUE TITLE
event 및 event_detail 페이지 css 전체 수정해야됨

### ISSUE THREAD

**Issue by kimc159** [sungkuk5420/CarRepairShopApp#87]
event 및 event_detail 페이지 css 전체 수정해야됨
이유는 meta에 viewport 적용 안시키고 퍼블리싱 했음
86브런치에서 작성하고 다시 올리겠음

**Comment by sungkuk5420** [comment]
이 이슈는 이전에 해결되어서 닫기처리합니다.
