### ISSUE TITLE
이벤트 페이지 폼으로 데이터 넘겼는데

### ISSUE THREAD

**Issue by kimc159** [sungkuk5420/CarRepairShopApp#98]
@sungkuk5420 
/event -> /event_detail
event 페이지 쿠폰 클릭시 event_detail 페이지로
 폼으로 데이터 넘겼는데 이런 방식이 맞는지 확인 부탁
그리고 detail 페이지에 가운데 가격 나오는 부분 35000원(100% OFF) 이부분 데이터 넘어올때
가져올 수 있는 부분인지 확인점 - 난 35000원 이 어디서 나오는지 모르겠음

**Comment by sungkuk5420** [comment]
@kimc159               
이슈로남길것이 아니라 풀리퀘 밑에 댓글로 남길것
